
server:
  port: 10000

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.atguigu.gulimall: debug
#alibaba:
#  cloud:
#    access-key: LTAI5tKupN4WwiioKnGUG7Dh
#    secret-key: wiXXClGhACe6V0eXb3OdgmXh1Glk40
#    oss:
#      endpoint: oss-cn-beijing.aliyuncs.com

